var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){var h=void 0,i=true,k=null,m=false,n=this,aa=function(a,b,c){a=a.split(".");c=c||n;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==h?c[d]=b:c=c[d]?c[d]:c[d]={}},o=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!=
"undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},p=function(a){return o(a)=="array"},ba=function(a){var b=o(a);return b=="array"||b=="object"&&typeof a.length=="number"},q=function(a){return typeof a=="string"},ca=function(a){a=o(a);return a=="object"||
a=="array"||a=="function"};Math.floor(Math.random()*2147483648).toString(36);
var da=function(a,b,c){return a.call.apply(a.bind,arguments)},ea=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}},s=function(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?da:ea;return s.apply(k,arguments)},fa=function(a,b){var c=
Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},ga=Date.now||function(){return+new Date},t=function(a,b,c){aa(a,b,c)},u=function(a,b,c){a[b]=c};var v=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},ha=function(a,b){return a=="true"?i:a=="false"?m:b},ia=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,ja=function(a,b){if(!a)return b;var c=a.match(ia);return c?c[0]:b};var ka=v("0",0),la=v("0",0),ma=v("0.01",0),na=v("0.01",0),oa=v("0",0),pa=v("0.01",0),qa=v("0",0);var ra=function(){var a="r20111019";return a},sa=ha("false",m),ta=ha("false",m),ua=ha("false",m);var va=function(){return ja("","googleads.g.doubleclick.net")},wa=function(){return ja("","pagead2.googlesyndication.com")},xa=function(){return ja("","pagead2.googlesyndication.com")};var Da=function(a,b){if(b)return a.replace(ya,"&amp;").replace(za,"&lt;").replace(Aa,"&gt;").replace(Ba,"&quot;");else{if(!Ca.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(ya,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(za,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(Aa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(Ba,"&quot;"));return a}},ya=/&/g,za=/</g,Aa=/>/g,Ba=/\"/g,Ca=/[&<>\"]/,Fa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(Ea,
function(a,e){var f=b[a];if(f)return f;if(e.charAt(0)=="#"){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}if(!f)c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1);return b[a]=f})},Ga=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},Ea=/&([^;\s<&]+);?/g,Ha=function(a,
b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Ia={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},Ja={"'":"\\'"},La=function(a){a=String(a);if(a.quote)return a.quote();else{for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=Ia[d]||(e>31&&e<127?d:Ka(d))}b.push('"');return b.join("")}},Ka=function(a){if(a in
Ja)return Ja[a];if(a in Ia)return Ja[a]=Ia[a];var b=a,c=a.charCodeAt(0);if(c>31&&c<127)b=a;else{if(c<256){if(b="\\x",c<16||c>256)b+="0"}else b="\\u",c<4096&&(b+="0");b+=c.toString(16).toUpperCase()}return Ja[a]=b},Ma=function(){var a=2147483648;return Math.floor(Math.random()*a).toString(36)+Math.abs(Math.floor(Math.random()*a)^ga()).toString(36)},Oa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=
Math.max(d.length,e.length),g=0;c==0&&g<f;g++){var j=d[g]||"",r=e[g]||"",l=RegExp("(\\d*)(\\D*)","g"),tc=RegExp("(\\d*)(\\D*)","g");do{var Y=l.exec(j)||["","",""],Z=tc.exec(r)||["","",""];if(Y[0].length==0&&Z[0].length==0)break;var c=Y[1].length==0?0:parseInt(Y[1],10),uc=Z[1].length==0?0:parseInt(Z[1],10),c=Na(c,uc)||Na(Y[2].length==0,Z[2].length==0)||Na(Y[2],Z[2])}while(c==0)}return c},Na=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var w=Array.prototype,Pa=w.indexOf?function(a,b,c){return w.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:c<0?Math.max(0,a.length+c):c;if(q(a))return!q(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Qa=w.forEach?function(a,b,c){w.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ra=function(a){return w.concat.apply(w,arguments)},Sa=function(a){if(p(a))return Ra(a);else{for(var b=[],c=0,
d=a.length;c<d;c++)b[c]=a[c];return b}},Ta=function(a,b,c){return arguments.length<=2?w.slice.call(a,b):w.slice.call(a,b,c)};var x=function(a,b){this.x=a!==h?a:0;this.y=b!==h?b:0};var y=function(a,b){this.width=a;this.height=b};y.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};y.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};y.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};y.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ua=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Va="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","),Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Va.length;f++)c=Va[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var z,Xa,Ya,Za,$a,ab=function(){return n.navigator?n.navigator.userAgent:k},bb=function(){$a=Za=Ya=Xa=z=m;var a;if(a=ab()){var b=n.navigator;z=a.indexOf("Opera")==0;Xa=!z&&a.indexOf("MSIE")!=-1;Za=(Ya=!z&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;$a=!z&&!Ya&&b.product=="Gecko"}};bb();
var cb=z,A=Xa,B=$a,C=Ya,db=Za,fb=function(){var a="",b;cb&&n.opera?(a=n.opera.version,a=typeof a=="function"?a():a):(B?b=/rv\:([^\);]+)(\)|;)/:A?b=/MSIE\s+([^\);]+)(\)|;)/:C&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(ab()))?a[1]:""));return A&&(b=eb(),b>parseFloat(a))?String(b):a},eb=function(){var a=n.document;return a?a.documentMode:h},gb=fb(),hb={},ib=function(a){return hb[a]||(hb[a]=Oa(gb,a)>=0)},jb={},kb=function(a){return jb[a]||(jb[a]=A&&document.documentMode&&document.documentMode>=a)};var lb,mb=!A||kb(9);!B&&!A||A&&kb(9)||B&&ib("1.9.1");A&&ib("9");var nb=function(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]},pb=function(a,b){var c=nb(a),d=Ta(arguments,1),d=ob(c,d);a.className=c.join(" ");return d},ob=function(a,b){for(var c=0,d=0;d<b.length;d++)Pa(a,b[d])>=0||(a.push(b[d]),c++);return c==b.length};var qb=function(a){return a?new D(E(a)):lb||(lb=new D)},rb=function(a){return q(a)?document.getElementById(a):a},sb=rb,ub=function(a,b){Ua(b,function(b,d){d=="style"?a.style.cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in tb?a.setAttribute(tb[d],b):d.lastIndexOf("aria-",0)==0?a.setAttribute(d,b):a[d]=b})},tb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",
type:"type"},wb=function(a){var b=a.document;if(C&&!ib("500")&&!db){typeof a.innerHeight=="undefined"&&(a=window);var b=a.innerHeight,c=a.document.documentElement.scrollHeight;a==a.top&&c<b&&(b-=15);return new y(a.innerWidth,b)}a=vb(b)?b.documentElement:b.body;return new y(a.clientWidth,a.clientHeight)},xb=function(a){var b=!C&&vb(a)?a.documentElement:a.body,a=a.parentWindow||a.defaultView;return new x(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},zb=function(a,b,c){return yb(document,
arguments)},yb=function(a,b){var c=b[0],d=b[1];if(!mb&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',Da(d.name),'"');if(d.type){c.push(' type="',Da(d.type),'"');var e={};Wa(e,d);d=e;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)q(d)?c.className=d:p(d)?pb.apply(k,[c].concat(d)):ub(c,d);b.length>2&&Ab(a,c,b,2);return c},Ab=function(a,b,c,d){function e(c){c&&b.appendChild(q(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];ba(f)&&!(ca(f)&&f.nodeType>0)?Qa(Bb(f)?Sa(f):
f,e):e(f)}},vb=function(a){return a.compatMode=="CSS1Compat"},Cb=function(a,b){a.appendChild(b)},Db=function(a,b){Ab(E(a),a,arguments,1)},Eb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):k},Fb=function(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},E=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},Bb=function(a){if(a&&
typeof a.length=="number")if(ca(a))return typeof a.item=="function"||typeof a.item=="string";else if(o(a)=="function")return typeof a.item=="function";return m},D=function(a){this.a=a||n.document||document};D.prototype.J=function(){return this.a};D.prototype.ha=function(a){return wb(a||this.ia()||window)};D.prototype.createElement=function(a){return this.a.createElement(a)};D.prototype.createTextNode=function(a){return this.a.createTextNode(a)};D.prototype.ka=function(){return vb(this.a)};
D.prototype.ia=function(){return this.a.parentWindow||this.a.defaultView};D.prototype.fa=function(){return!C&&vb(this.a)?this.a.documentElement:this.a.body};D.prototype.K=function(){return xb(this.a)};D.prototype.appendChild=Cb;D.prototype.append=Db;D.prototype.removeNode=Eb;D.prototype.contains=Fb;var F=document,G=window,Gb=function(a){var b=k;if((a=a.getElementsByTagName("script"))&&a.length)b=a[a.length-1],b=b.parentNode;return b},Hb=Gb(F);xa();var H=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(k,a[c],c,a)},Ib=function(a){return!!a&&typeof a=="function"&&!!a.call},Jb=function(a){return!!a&&(typeof a=="object"||typeof a=="function")},Kb=function(a,b){if(!a)return m;var c=i;H(b,function(b,e){if(!c||!(e in a)||typeof b!=typeof a[e])c=m});return c},Lb=function(a,b){if(arguments.length<2)return a.length;for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c]);return a.length};
function I(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Mb(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onreadystatechange!==h?d.onreadystatechange=function(){if(d.readyState=="complete"||d.readyState=="loaded")try{b()}catch(a){}}:d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return m;window.setTimeout(function(){e.appendChild(d)},0);return i}
function Nb(a,b){if(a.attachEvent)return a.attachEvent("onload",b),i;return a.addEventListener?(a.addEventListener("load",b,m),i):m}var Ob=function(a){if(!("google_onload_fired"in a))a.google_onload_fired=m,Nb(a,function(){a.google_onload_fired=i})};function Pb(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}var Qb={};
function Rb(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var a=3,b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(c){b=k}return a.toString()}else if(("msie"in Qb?Qb.msie:Qb.msie=navigator.userAgent.toLowerCase().indexOf("msie")!=-1)&&!window.opera){b=
k;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=6,b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b)return a=b.GetVariable("$version").split(" ")[1],a.replace(/,/g,".")}return"0"}function Sb(a){var b=a.google_ad_format;return b?b.indexOf("_0ads")>0:a.google_ad_output!="html"&&a.google_num_radlinks>0}
function J(a){return!!a&&a.indexOf("_sdo")!=-1}
var Tb=function(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b)return c=Math.floor(c/b*a.length),a[c]}return k},Ub=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen)a.u_h=window.screen.height,a.u_w=window.screen.width,a.u_ah=window.screen.availHeight,a.u_aw=window.screen.availWidth,a.u_cd=window.screen.colorDepth;if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},
Vb=function(a,b){var c=b||G;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new y(-1,-1):wb(c||window)}catch(d){return new y(-12245933,-12245933)}},Wb=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var f=a.charCodeAt(e);d^=(d<<5)+(d>>2)+f&4294967295}return d>0?d:4294967296+d},Xb=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=i,a=Vb(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Wb(b.join(""))},
Yb=function(a){if(!a)return"";for(var b=[],c=0;a&&c<25;a=a.parentNode,++c)b.push(a.id||"");return b.join()},Zb=function(a){try{return!!a.document}catch(b){return m}},ac=function(a){if(!a)return k;a&&a.id&&a.id.indexOf("aswift_")==0&&(a=$b(a));return a||k},bc=function(a){return!a?"":(a=ac(a))&&a.src||""},$b=function(a){return a=a.contentWindow.document.getElementsByTagName("iframe")[0]},cc=function(a,b){if(!a)return k;var c=b.getElementById("google_ads_div_"+a+"_ad_container");c||(c=b.getElementById("google_ads_div_"+
a));return c};var dc=function(a,b,c,d){b="border:none;height:"+c+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+b+"px";a=['<ins style="display:inline-table;',b,'">','<ins id="',a,'" style="display:block;',b,'">',d,"</ins></ins>"];return a.join("")};var ec=function(a,b,c){b=s(b,n,a);a=window.onerror;window.onerror=b;try{c()}catch(d){var c=d.toString(),e="";d.fileName&&(e=d.fileName);var f=-1;if(d.lineNumber)f=d.lineNumber;b=b(c,e,f);if(!b)throw d;}window.onerror=a};t("google_protectAndRun",ec);
var gc=function(a,b,c,d){if(Math.random()<0.01){var e=F,a=["http://",wa(),"/pagead/gen_204","?id=jserror","&jscb=",sa?1:0,"&jscd=",ta?1:0,"&context=",I(a),"&msg=",I(b),"&file=",I(c),"&line=",I(d.toString()),"&url=",I(e.URL.substring(0,512)),"&ref=",I(e.referrer.substring(0,512))];a.push(fc());Pb(G,a.join(""))}return!ua};t("google_handleError",gc);
var ic=function(a){hc|=a},hc=0,fc=function(){var a=["&client=",I(G.google_ad_client),"&format=",I(G.google_ad_format),"&slotname=",I(G.google_ad_slot),"&output=",I(G.google_ad_output),"&ad_type=",I(G.google_ad_type)];return a.join("")};var jc=function(a){var b="google_test";try{var c=a[b];a[b]=!c;if(a[b]===!c)return a[b]=c,i}catch(d){}return m},kc=function(a){for(;a!=a.parent&&jc(a.parent);)a=a.parent;return a},lc=k,mc=function(){lc||(lc=kc(window));return lc};var K=function(a){this.u=[];this.c=a||window;this.e=0;this.t=k},nc=function(a,b){this.fn=a;this.win=b};K.prototype.enqueue=function(a,b){this.e==0&&this.u.length==0&&(!b||b==window)?(this.e=2,this.W(new nc(a,window))):this.q(a,b)};K.prototype.q=function(a,b){this.u.push(new nc(a,b||this.c));this.z()};K.prototype.U=function(a){this.e=1;if(a)this.t=this.c.setTimeout(s(this.w,this),a)};K.prototype.w=function(){if(this.e==1){if(this.t!=k)this.c.clearTimeout(this.t),this.t=k;this.e=0}this.z()};
K.prototype.statusz=function(){return i};u(K.prototype,"nq",K.prototype.enqueue);u(K.prototype,"nqa",K.prototype.q);u(K.prototype,"al",K.prototype.U);u(K.prototype,"rl",K.prototype.w);u(K.prototype,"sz",K.prototype.statusz);K.prototype.z=function(){this.c.setTimeout(s(this.ua,this),0)};K.prototype.ua=function(){if(this.e==0&&this.u.length){var a=this.u.shift();this.e=2;a.win.setTimeout(s(this.W,this,a),0);this.z()}};K.prototype.W=function(a){this.e=0;a.fn()};
var oc=function(a){try{return a.sz()}catch(b){return m}},pc=function(){var a=mc().google_jobrunner;Jb(a)&&oc(a)&&Ib(a.nq)&&Ib(a.nqa)&&Ib(a.al)&&Ib(a.rl)&&a.rl()};var L=!!window.google_async_iframe_id,M=L&&window.parent||window,N=function(){if(L&&!Zb(M)){for(var a="."+F.domain;a.split(".").length>2&&!Zb(M);)F.domain=a=a.substr(a.indexOf(".")+1),M=window.parent;Zb(M)||(M=window)}return M},qc=function(a){L&&a!=a.parent&&(pc(),a.google_async_iframe_close&&a.setTimeout(function(){a.document.close()},0))},rc=function(){if(!L)return k;var a=window.google_async_iframe_id;if(a){for(var a=N().document.getElementById(a),b=0;a&&b<3;++b)a=a.parentNode;return a}return k};var O=function(a){this.defaultBucket=[];this.layers={};for(var b=0,c=arguments.length;b<c;++b)this.layers[arguments[b]]=""},sc=function(a){for(var b=new O,c=0,d=a.defaultBucket.length;c<d;++c)b.defaultBucket.push(a.defaultBucket[c]);H(a.layers,s(O.prototype.H,b));return b};O.prototype.statusz=function(){return i};O.prototype.H=function(a,b){this.layers[b]=a};
O.prototype.X=function(a,b){if(a=="")return"";if(!b)return this.defaultBucket.push(a),a;return this.layers.hasOwnProperty(b)?this.layers[b]=a:""};O.prototype.C=function(a,b,c){return this.la(c)&&!(Math.random()<1.0E-4)&&Math.random()<b?(b=Math.floor(Math.random()*a.length),this.X(a[b],c)):""};O.prototype.la=function(a){return!a?i:this.layers.hasOwnProperty(a)&&this.layers[a]==""};O.prototype.d=function(a){return this.layers.hasOwnProperty(a)?this.layers[a]:""};O.prototype.geil=O.prototype.d;
O.prototype.ga=function(){var a=[],b=function(b){b!=""&&a.push(b)};H(this.layers,b);return this.defaultBucket.length>0&&a.length>0?this.defaultBucket.join(",")+","+a.join(","):this.defaultBucket.join(",")+a.join(",")};var wc=function(a){this.S=a;vc(this)},xc={google_persistent_state:i,google_persistent_state_async:i},yc={},zc=function(a){a=a&&xc[a]?a:L?"google_persistent_state_async":"google_persistent_state";if(yc[a])return yc[a];if(a=="google_persistent_state_async")var b=N(),c={};else c=b=N();var d=b[a];return typeof d!="object"||typeof d.S!="object"?b[a]=yc[a]=new wc(c):yc[a]=d},vc=function(a){P(a,3,k);P(a,4,0);P(a,5,0);P(a,6,0);P(a,7,(new Date).getTime());P(a,8,{});P(a,9,{});P(a,10,{});P(a,11,[]);P(a,12,0);
P(a,14,{})},Ac=function(a){switch(a){case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";case 12:return"google_num_slot_to_show";case 14:return"gaGlobal"}},Q=function(a,b){var c=Ac(b);return c=
a.S[c]},R=function(a,b,c){return a.S[Ac(b)]=c},P=function(a,b,c){a=a.S;b=Ac(b);return a[b]===h?a[b]=c:a[b]},Bc=function(a,b){return R(a,3,b)};var Cc,Dc,Ec=function(a){try{return a.statusz()}catch(b){return m}},S=function(){if(Cc&&Ec(Cc))return Cc;var a=zc(),b=Q(a,3);return!b||!Jb(b)||!Kb(b,O.prototype)||!Ec(b)?Cc=Bc(a,new O(1,2,3,4,5,6,7,8)):Cc=b},Fc=function(){Dc||(Dc=sc(S()));return Dc},Gc={CONTROL:"86748120",EXPERIMENT_BADGE_AFTER_TITLE:"86748121",EXPERIMENT_BADGE_AFTER_TEXT:"86748122",EXPERIMENT_BADGE_BENEATH_CREATIVE:"86748123"},Hc={CONTROL:"86726840",EXPERIMENT_BADGE_AFTER_TITLE:"86726841",EXPERIMENT_BADGE_BENEATH_CREATIVE:"86726842"};var Ic={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Jc(a){if(ua)return m;a=a.google_page_location||a.google_page_url;if(!a)return m;a=a.toString();a.indexOf("http://")==0?a=a.substring(7,a.length):a.indexOf("https://")==0&&(a=a.substring(8,a.length));var b=a.indexOf("/");if(b==-1)b=a.length;a=a.substring(0,b);a=a.split(".");b=m;a.length>=3&&(b=a[a.length-3]in Ic);a.length>=2&&(b=b||a[a.length-2]in Ic);return b}
var Kc=function(a){var b=S();return b.d(1)=="44901228"?m:b.d(1)=="44901229"||Math.random()<la?1==Math.floor(a/2)%2:m};var T=function(a,b){this.i=a;this.s=b?b.s:[];this.g=b?b.g:[];this.k=b?b.k:[];this.l=b?b.l:0;this.h=b?b.h:[];this.R=b?b.R:m;this.j=b?b.j:"";this.T=b?b.T:0;this.D=b?b.D:"";this.Q=b?b.Q:m};T.prototype.qa=function(a,b){var c=this.i[b],d=this.s;this.i[b]=function(b){if(b&&b.length>0){var f=b.length>1?b[1].url:k;d.push([a,b[0].url.indexOf("&")!=-1?"document"in n?Fa(b[0].url):Ga(b[0].url):b[0].url,f])}c(b)}};T.prototype.pa=function(a){this.g.push(a)};T.prototype.ra=function(a){this.k.push(a)};
var Lc="http://"+xa()+"/pagead/osd.js";T.prototype.na=function(){if(!this.R)Ob(N()),Mb(Lc),this.R=i};T.prototype.ca=function(a){if(this.g.length>0)if(this.Q)for(var b=this.i.document.getElementsByTagName("iframe"),c=0;c<b.length;c++){var d=b[c]&&b[c].name&&b[c].name.indexOf("google_ads_iframe_")==0?b[c].src||"":"";d&&a(b[c],d)}else for(c=0;c<this.g.length;c++)(b=this.i.document.getElementById("google_ads_frame"+this.g[c])||this.i.document.getElementById("aswift_"+(this.g[c]-1)))&&a(b,bc(b))};
T.prototype.G=function(a,b){var c=this.s;if(c.length>0)for(var d=a.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d[e].href.indexOf(c[f][1])>=0){var g=d[e].parentNode;if(c[f][2])for(var j=g,r=0;r<4;r++){if(j.innerHTML.indexOf(c[f][2])>=0){g=j;break}j=j.parentNode}b(g,c[f][0]);c.splice(f,1);break}if(c.length>0&&a!=mc())try{this.G(a.parent,b)}catch(l){}};
T.prototype.da=function(a){for(var b=0;b<this.k.length;b++){var c=this.k[b],d=Mc(c);d&&(d=cc(d,this.i.document))&&a(d,c)}};T.prototype.F=function(a){this.G(this.i,a);this.da(a);this.ca(a)};
T.prototype.A=function(a){if(this.b())return this.b();var b=window.google_enable_ose,c;if(b===i)c=2;else if(b!==m&&((c=Tb([1],ma))||(c=Tb([2],na)),!c))b=["35025001","35025002"],this.j=Tb(b,oa),this.j=="35025002"&&(c=3);if(!c)return 0;this.T=c;this.h=["html","js","json_html"];switch(this.b()){case 1:this.l=1;break;case 2:this.l=0;break;case 3:this.l=3;break;default:this.h=[]}this.D=String(a||0);return this.b()};T.prototype.P=function(){return this.l};T.prototype.L=function(){return this.j};
T.prototype.r=function(){return this.j};T.prototype.b=function(){return this.T};T.prototype.I=function(){return this.D};T.prototype.O=function(){return this.s.length+this.g.length+this.k.length};T.prototype.Y=function(a){this.h=a};T.prototype.v=function(a,b,c,d){if(this.h.length>0){for(var e=0;e<this.h.length;e++)if(this.h[e]==a)this.Q=c,a=="js"?this.qa(b,"google_ad_request_done"):a=="html"?this.pa(d):a=="json_html"&&this.ra(b);this.na()}};
var Mc=function(a){return(a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2?a[1]:""},Nc=function(){var a=N(),b=a.__google_ad_urls;return!b?a.__google_ad_urls=new T(a):b};t("Goog_AdSense_getAdAdapterInstance",Nc);t("Goog_AdSense_OsdAdapter",T);t("Goog_AdSense_OsdAdapter.prototype.numBlocks",T.prototype.O);t("Goog_AdSense_OsdAdapter.prototype.findBlocks",T.prototype.F);t("Goog_AdSense_OsdAdapter.prototype.getOsdMode",T.prototype.P);t("Goog_AdSense_OsdAdapter.prototype.getEid",T.prototype.L);
t("Goog_AdSense_OsdAdapter.prototype.getOseExpId",T.prototype.r);t("Goog_AdSense_OsdAdapter.prototype.getOseId",T.prototype.b);t("Goog_AdSense_OsdAdapter.prototype.getCorrelator",T.prototype.I);t("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",T.prototype.Y);t("Goog_AdSense_OsdAdapter.prototype.setupOse",T.prototype.A);t("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",T.prototype.v);var Oc=function(a){this.c=a;a.google_iframe_oncopy||(a.google_iframe_oncopy={handlers:{},log:[],img:Math.random()<0.01?[]:k});this.B=a.google_iframe_oncopy;a.setTimeout(s(this.sa,this),3E4)};Da("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){i+='.call';setTimeout(h,0)}else if(h.match){i+='.nav';w.location.replace(h)}s.log&&s.log.push(i)}");
Oc.prototype.set=function(a,b){this.B.handlers[a]=b;this.c.addEventListener&&this.c.addEventListener("load",s(this.ea,this,a),m)};Oc.prototype.ea=function(a){var a=this.c.document.getElementById(a),b=a.contentWindow.document;if(a.onload&&b&&(!b.body||!b.body.firstChild))a.onload()};
Oc.prototype.sa=function(){if(this.B.img){var a=this.B.log,b=this.c.document;if(a.length)b=["http://",wa(),"/pagead/gen_204?id=iframecopy&log=",I(a.join("-")),"&url=",I(b.URL.substring(0,512)),"&ref=",I(b.referrer.substring(0,512))].join(""),a.length=0,a=new Image,this.B.img.push(a),a.src=b}};var Pc=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};Pc.prototype.contains=function(a){return Qc(this,a)};Pc.prototype.expand=function(a,b,c,d){ca(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=c,this.left-=d);return this};var Qc=function(a,b){return!a||!b?m:b instanceof Pc?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom};var Rc=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};Rc.prototype.ta=function(){var a=this.left+this.width,b=this.top+this.height;return new Pc(this.top,a,b,this.left)};Rc.prototype.contains=function(a){return a instanceof Rc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};var Sc=function(a,b){var c=E(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,k))?c[b]||c.getPropertyValue(b):""},U=function(a,b){return Sc(a,b)||(a.currentStyle?a.currentStyle[b]:k)||a.style[b]},Tc=function(a){a=a?a.nodeType==9?a:E(a):document;return A&&!kb(9)&&!qb(a).ka()?a.body:a.documentElement},Uc=function(a){var b=a.getBoundingClientRect();if(A)a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop;return b},Vc=function(a){if(A)return a.offsetParent;for(var b=E(a),c=U(a,"position"),d=c=="fixed"||c=="absolute",a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=U(a,"position"),d=d&&c=="static"&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"||c=="relative"))return a;return k},Yc=function(a){for(var b=new Pc(0,Infinity,Infinity,0),c=qb(a),d=c.J().body,e=c.J().documentElement,f=c.fa();a=Vc(a);)if((!A||a.clientWidth!=
0)&&(!C||a.clientHeight!=0||a!=d)&&a!=d&&a!=e&&U(a,"overflow")!="visible"){var g=Wc(a),j=Xc(a);g.x+=j.x;g.y+=j.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=c.ha();b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return b.top>=0&&b.left>=0&&b.bottom>b.top&&b.right>b.left?b:k},Xc=function(a){if(B&&
!ib("1.9")){var b=parseFloat(Sc(a,"borderLeftWidth"));if("rtl"==U(a,"direction")){var c=a.offsetWidth-a.clientWidth-b-parseFloat(Sc(a,"borderRightWidth"));b+=c}return new x(b,parseFloat(Sc(a,"borderTopWidth")))}return new x(a.clientLeft,a.clientTop)},Wc=function(a){var b,c=E(a),d=U(a,"position"),e=B&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new x(0,0),g=Tc(c);if(a==g)return f;if(a.getBoundingClientRect)b=Uc(a),a=qb(c).K(),f.x=
b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(g),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(C&&U(b,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(cb||C&&d=="absolute")f.y-=c.body.offsetTop;for(b=a;(b=Vc(b))&&b!=c.body&&b!=g;)if(f.x-=b.scrollLeft,!cb||b.tagName!="TR")f.y-=b.scrollTop}return f},
$c=function(a,b){var c=new x(0,0),d=E(a)?E(a).parentWindow||E(a).defaultView:window,e=a;do{var f=d==b?Wc(e):Zc(e);c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c},Zc=function(a){var b=new x;if(a.nodeType==1)if(a.getBoundingClientRect)a=Uc(a),b.x=a.left,b.y=a.top;else{var c=qb(a).K(),a=Wc(a);b.x=a.x-c.x;b.y=a.y-c.y}else{var c=o(a.getBrowserEvent)=="function",d=a;a.targetTouches?d=a.targetTouches[0]:c&&a.getBrowserEvent().targetTouches&&(d=a.getBrowserEvent().targetTouches[0]);
b.x=d.clientX;b.y=d.clientY}return b},bd=function(a){if(U(a,"display")!="none")return ad(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=ad(a);b.display=c;b.position=e;b.visibility=d;return a},ad=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=C&&!b&&!c;return(b===h||d)&&a.getBoundingClientRect?(a=Uc(a),new y(a.right-a.left,a.bottom-a.top)):new y(b,c)},cd=function(a){var b=Wc(a),a=bd(a);return new Rc(b.x,b.y,a.width,a.height)},
dd=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b}},ed=function(a){var b=E(a),c="";if(b.body.createTextRange){b=b.body.createTextRange();b.moveToElementText(a);try{c=b.queryCommandValue("FontName")}catch(d){c=""}}c||(c=U(a,"fontFamily"));a=c.split(",");a.length>1&&(c=a[0]);return Ha(c,"\"'")},fd=/[^\d]+$/,gd=function(a){return(a=a.match(fd))&&
a[0]||k},hd={cm:1,"in":1,mm:1,pc:1,pt:1},id={em:1,ex:1},jd=function(a){var b=U(a,"fontSize"),c=gd(b);if(b&&"px"==c)return parseInt(b,10);if(A)if(c in hd)return dd(a,b,"left","pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in id)return a=a.parentNode,c=U(a,"fontSize"),dd(a,b==c?"1em":b,"left","pixelLeft");c=zb("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Cb(a,c);b=c.offsetHeight;Eb(c);return b};var kd={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ld={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip",google_tfs:"tfs",google_tl:"tl"},md={google_only_pyv_ads:"pyv",google_only_userchoice_ads:"uc",google_scs:"scs",google_with_pyv_ads:"withpyv",google_previous_watch:"p_w",google_previous_searches:"p_s"};function nd(a,b){try{return a.top.document==b}catch(c){}return m}function od(a){var b=2;try{b=a.top.document==a.document?0:a.top.document?1:2}catch(c){}return b}function pd(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(nd(a,b))return m;var e=b.documentElement;if(c&&d){var f=1,g=1;if(a.innerHeight)f=a.innerWidth,g=a.innerHeight;else if(e&&e.clientHeight)f=e.clientWidth,g=e.clientHeight;else if(b.body)f=b.body.clientWidth,g=b.body.clientHeight;if(g>2*d||f>2*c)return m}return i}
function qd(a,b){H(b,function(b,d){a["google_"+d]=b})}function rd(a,b){var c=od(N()),d=!!a.google_referrer_url,e=4;!b&&c==1?e=5:!b&&c==2?e=6:b&&c==1?e=7:b&&c==2&&(e=8);e+=5*d;return""+e}function sd(a,b,c){a.page_url=!c?b.URL:b.referrer;a.page_location=k}function td(a,b,c,d){a.page_url=b.google_page_url;a.page_location=(!d?c.URL:c.referrer)||"EMPTY"}
function ud(a,b){var c={},d=pd(N(),b,a.google_ad_width,a.google_ad_height);c.iframing=rd(a,d);a.google_page_url?td(c,a,b,d):sd(c,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1E3:k;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function vd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=k;b.page_url=c;b.page_location=a.URL;b.last_modified_time=k;b.referrer_url=c;return b}
function wd(a){var b=xd(a,N().document);qd(a,b)}function xd(a,b){var c;return c=a.google_page_url==k&&yd[b.domain]?vd(b):ud(a,b)}var yd={"ad.yieldmanager.com":i};var Bd=function(){if(window.google_ad_output==k)window.google_ad_output="html";if(J(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a)window.google_ad_width=parseInt(a[1],10),window.google_ad_height=parseInt(a[2],10),window.google_ad_output="html"}window.google_ad_format=zd(window.google_ad_format,String(window.google_ad_output),Number(window.google_ad_width),Number(window.google_ad_height),window.google_ad_slot,!!window.google_override_format);window.google_ad_client=
Ad(window.google_ad_format,window.google_ad_client);wd(window);if(window.google_flash_version==k)window.google_flash_version=Rb();window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();if(p(window.google_color_bg))window.google_color_bg=V(window.google_color_bg,a);if(p(window.google_color_text))window.google_color_text=V(window.google_color_text,a);if(p(window.google_color_link))window.google_color_link=
V(window.google_color_link,a);if(p(window.google_color_url))window.google_color_url=V(window.google_color_url,a);if(p(window.google_color_border))window.google_color_border=V(window.google_color_border,a);if(p(window.google_color_line))window.google_color_line=V(window.google_color_line,a)},Cd=function(a){H(kd,function(b,c){a[c]=k});H(ld,function(b,c){a[c]=k});H(md,function(b,c){a[c]=k});a.google_container_id=k;a.google_enable_async=k;a.google_eids=k;a.google_page_location=k;a.google_referrer_url=
k;a.google_show_ads_impl=k;a.google_ad_region=k;a.google_gl=k;a.google_iframe_name=k;a.google_loader_used=k},V=function(a,b){ic(2);return a[b%a.length]},Ad=function(a,b){if(!b)return"";b=b.toLowerCase();return b=J(a)?Dd(b):Ed(b)},Ed=function(a){a&&a.substring(0,3)!="ca-"&&(a="ca-"+a);return a},Dd=function(a){a&&a.substring(0,7)!="ca-aff-"&&(a="ca-aff-"+a);return a},zd=function(a,b,c,d,e,f){!a&&b=="html"&&(a=c+"x"+d);return a=(!a?0:!e||f)?a.toLowerCase():""};var W=navigator;
function Fd(a,b,c,d,e){var f=Math.round((new Date).getTime()/1E3),g=window.google_analytics_domain_name,a=typeof g=="undefined"?Gd("auto",a):Gd(g,a),j=b.indexOf("__utma="+a+".")>-1,g=b.indexOf("__utmb="+a)>-1,r=b.indexOf("__utmc="+a)>-1,l=zc("google_persistent_state"),l=Q(l,14)||R(l,14,{});if(j){b=b.split("__utma="+a+".")[1].split(";")[0].split(".");if(g&&r)l.sid=b[3]+"";else if(!l.sid)l.sid=f+"";l.vid=b[0]+"."+b[1];l.from_cookie=i}else{if(!l.sid)l.sid=f+"";if(!l.vid)l.vid=(Math.round(Math.random()*2147483647)^
Hd(b,c,d,e)&2147483647)+"."+f;l.from_cookie=m}l.dh=a;if(!l.hid)l.hid=Math.round(Math.random()*2147483647);return l}function Hd(a,b,c,d){var e=[W.appName,W.version,W.language?W.language:W.browserLanguage,W.platform,W.userAgent,W.javaEnabled()?1:0].join("");c?e+=c.width+"x"+c.height+c.colorDepth:window.java&&(c=java.awt.Toolkit.getDefaultToolkit().getScreenSize(),e+=c.screen.width+"x"+c.screen.height);e+=a;e+=d||"";for(a=e.length;b>0;)e+=b--^a++;return Id(e)}
function Id(a){var b=1,c=0,d;if(!(a==h||a=="")){b=0;for(d=a.length-1;d>=0;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=c!=0?b^c>>21:b}return b}function Gd(a,b){if(!a||a=="none")return 1;a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return Id(a.toLowerCase())};var X=function(a,b,c,d,e,f){this.ma=m;this.Z=a;this.V=e;this.$=f;this.ya=b;this.o=+c;this.n=+d;this.p=[]};X.prototype.getId=function(){return this.Z};X.prototype.collapse=function(){var a=this.N();if(a)this.va(),this.ma=m};X.prototype.m=function(a){this.f(a,"zIndex","999999")};X.prototype.ba=function(a,b,c){this.f(a,"width",b+"px");this.f(a,"height",c+"px");this.m(a)};
X.prototype.M=function(){var a=[],b=this.N();if(!b)return a;a.push(b);this.V&&this.$&&a.push(this.V.document.getElementById(this.$));return a};
X.prototype.expand=function(a,b,c){var d=this.M();if(!(d.length<=0)){for(var e=0,f=d.length;e<f;++e)this.ba(d[e],a,b);d=d[d.length-1];a>this.o&&(c==0||c==3)&&this.f(d,"left","-"+(a-this.o)+"px");b>this.n&&(c==1||c==0)&&this.f(d,"top","-"+(b-this.n)+"px");a=d.parentNode;b=a.parentNode;a.nodeName.toLowerCase()=="ins"&&(this.m(a),this.m(b));for(a=b.parentNode;a&&a.style;a=a.parentNode){if(a.nodeName.toLowerCase()=="body")break;a.style.overflow!="visible"&&this.f(a,"overflow","visible")}this.ma=i}};
X.prototype.aa=function(a,b){var c=this.M(),c=c[c.length-1],c=Zc(c),d=this.V||window,d=wb(d||window),e=a-this.o,f=b-this.n,g=c.y,f=f>g,j=d.height-(c.y+this.n),g=f||j>=g,f=c.x,e=e>f,c=d.width-(c.x+this.o),c=e||c>=f,d=2;g&&!c?d=3:!g&&c?d=1:!g&&!c&&(d=0);return d};X.prototype.N=function(){if(!this.ja)this.ja=F.getElementById(this.Z);return this.ja};X.prototype.f=function(a,b,c){this.p.push(new Jd(a,b,c))};X.prototype.va=function(){for(var a=0,b=this.p.length;a<b;a++)this.p[a].undo();this.p.length=0};
var Jd=function(a,b,c){this.oa=a;this.wa=b;this.xa=a.style[b];this.oa.style[b]=c};Jd.prototype.undo=function(){this.oa.style[this.wa]=this.xa};var Kd=function(a,b){var c=a.aa(b.width,b.height);a.expand(b.width,b.height,c);return{width:b.width,height:b.height,direction:c}},Ld=function(a){a.collapse();return{}},Md=function(a,b){var c={},d=new X(b.id,"",b.width,b.height,b.topMostFriendlyWindow,b.friendlyIframeId);c.expand=fa(Kd,d);c.collapse=fa(Ld,d);d={};iframes.open(a,b,d,c)},Nd=function(){iframes.setHandler("expandable",{onOpen:function(a){var b=a.getOpenParams(),c=b.container,d=b.width,e=b.height,f=b.id,g=f+"_anchor";if(b.friendlyIframeId)c=
document.createElement("div"),document.body.appendChild(c);else{var j=dc(g,d,e,"");c?(c.innerHTML=j,c=c.firstChild.firstChild):(document.write(j),c=document.getElementById(g))}return a=a.openInto(c,{id:f,width:d,height:e,style:b.cssStyle})},onReady:function(){},onClose:function(){}})};var Od=(new Date).getTime(),Pd=function(a){var b=(new Date).getTime()-Od,b="&dtd="+(b<1E4?b:"M");return a+b};var Qd=function(a){var b="google_unique_id";a[b]?++a[b]:a[b]=1;return a[b]},Rd=function(a){var b="google_unique_id",a=a[b];return typeof a=="number"?a:0},Sd=function(a){return a.google_slot_list&&a.google_slot_list.join?a.google_slot_list.join(",").slice(-100):""};var $={};function Td(a,b){a&&a!=""&&(b==1?$[b]?$[b]+=","+a:$[b]=a:$[b]=a)}function Ud(){var a=[];H($,function(b){a.push(b)});return a.join(",")}function Vd(a,b){if(p(a))for(var c=0;c<a.length;c++)q(a[c])&&Td(a[c],b)}var Wd=m;function Xd(a){return a!=k?'"'+a+'"':'""'}var Yd=function(a,b){var c=b.slice(-1),d=c=="?"||c=="#"?"":"&",e=[b],c=function(a,b){if(a||a===0||a===m)typeof a=="boolean"&&(a=a?1:0),Lb(e,d,b,"=",I(a)),d="&"};H(a,c);return e.join("")};
function Zd(){var a;G.google_ad_output=="html"&&!Sb(G)&&!J(G.google_ad_format)&&!$[0]&&(a=["6083035","6083034"],a=Tb(a,qa)||"",Td(a,0));return a=="6083035"}var $d=function(){var a=Nc(),b=zc();return a.A(Q(b,7))};
function ae(a,b,c,d){L||Qd(a);var e=Rd(a),c=Yd({ifi:e},c),c=c.substring(0,1991),c=c.replace(/%\w?$/,""),f="script",g="google_ads_frame"+e,j=S().d(5);if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Xd(Pd(c))+"></"+f+">");else if(a.google_ad_output=="html"){var f=Wd?c.replace(/&ea=[^&]*/,"")+"&ea=0":c,f=['<iframe id="',g,'" name="',g,'" width=',Xd(String(a.google_ad_width))," height=",
Xd(String(a.google_ad_height)),' frameborder="0" src=',Xd(Pd(f)),' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>'].join(""),r=Gc,l=Hc,d=a.google_container_id||d||k;typeof iframes=="object"&&typeof iframes.open=="function"&&(j=="33895222"||j=="33895223"||j=="33895225"||j==r.CONTROL||j==r.EXPERIMENT_BADGE_AFTER_TITLE||j==r.EXPERIMENT_BADGE_AFTER_TEXT||j==r.EXPERIMENT_BADGE_BENEATH_CREATIVE||j==l.CONTROL||j==l.EXPERIMENT_BADGE_AFTER_TITLE||j==
l.EXPERIMENT_BADGE_BENEATH_CREATIVE)?(Nd(),iframes.setVersionOverride("gcm_01fa0dcbd17f41ae40e2e164313785ce.js"),g={style:"expandable",id:g,rpcToken:"adsense_rpc_key",width:a.google_ad_width,height:a.google_ad_height,cssStyle:"left:0;position:absolute;top:0",topMostFriendlyWindow:N(),friendlyIframeId:a.google_async_iframe_id},Md(Pd(c),g)):Wd&&typeof ExpandableAdSlotFactory=="object"&&typeof ExpandableAdSlotFactory.createIframe=="function"?a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe(g,
Pd(c),a.google_ad_width,a.google_ad_height,d,N(),a.google_async_iframe_id):a.google_container_id?be(a.google_container_id,b,f):b.write(f);L&&ce(a.google_async_iframe_id,f)}j=="30143103"&&e==1&&!a.google_container_id&&b.write('<iframe height=1 src="https://web.archive.org/web/20111027125050/http://pagead2.googlesyndication.com/pagead/s/iframes_api_loader.html" style="position:absolute;visibility:hidden" width=1></iframe>');return c}
var ce=function(a,b){var c="javascript:"+La(["<!DOCTYPE html><html><body>",b,"</body></html>"].join("")),d=N();(new Oc(d)).set(a,c)};function de(a){Cd(a)}function ee(a){var b=Fc().d(2)=="44901217";if(!fe(b))return m;var b=Zd(),c=!Jc(window)?Kc(Rd(window))?"http://"+ja("","googleads2.g.doubleclick.net"):"http://"+va():"http://"+wa(),a=ge(a),b=c+he(a.google_ad_format,b);window.google_ad_url=Yd(a,b);return i}
var le=function(a){a.dt=Od;if(L&&window.google_bpp)a.bpp=window.google_bpp;a.shv=ra();var b=!!window.google_test_1,c=!!window.google_test_2;b&&(a.tsi=c?"3":"2");a.jsv="/r20110914".replace("/","");window.google_loader_used&&(a.saldr=1);var b=zc(),c=Q(b,8),d=window.google_ad_section,e=window.google_ad_format,f=window.google_ad_slot;c[d]&&(J(e)||(a.prev_fmts=c[d]));var g=Q(b,9);g[d]&&(a.prev_slotnames=g[d].toLowerCase());e?J(e)||(c[d]?c[d]+=
","+e:c[d]=e):f&&(g[d]?g[d]+=","+f:g[d]=f);a.correlator=Q(b,7);if(window.google_ad_channel){c=Q(b,10);d="";e=window.google_ad_channel.split(ie);for(f=0;f<e.length;f++)g=e[f],c[g]?d+=g+"+":c[g]=i;a.pv_ch=d}if(window.google_ad_host_channel)b=je(window.google_ad_host_channel,Q(b,11)),a.pv_h_ch=b;sa&&(a.jscb=1);ta&&(a.jscd=1);a.frm=window.google_iframing;a.adk=ke();b=N().document;b=Fd(b.domain,b.cookie,window.history.length,window.screen,b.referrer);a.ga_vid=b.vid;a.ga_sid=b.sid;a.ga_hid=b.hid;a.ga_fc=
b.from_cookie;a.ga_wpids=window.google_analytics_uacct},me=function(a){var b=i;if(b=Vb(b))a.biw=b.width,a.bih=b.height},ke=function(){var a=[];Lb(a,G.google_ad_slot,G.google_ad_format,G.google_ad_type,G.google_ad_width,G.google_ad_height);var b=L?rc():Hb;b&&(b=Yb(b))&&a.push(b);b=0;a&&(b=Wb(a.join(":")));return b.toString()},ne=function(a){var b=Xb(N());b!=0&&(a.ifk=b.toString())},oe=function(a){var b=Nc();(b=b.b())&&(a.oid=b)},pe=function(a){a.prodhost=va()};
function je(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var g=c[f].split(ie);b[f]||(b[f]={});for(var j="",r=0;r<g.length;r++){var l=g[r];l!=""&&(b[f][l]?j+="+"+l:b[f][l]=i)}j=j.slice(1);e[f]=j;j!=""&&(d=f)}c="";if(d>-1){for(f=0;f<d;f++)c+=e[f]+"|";c+=e[d]}return c}function qe(){var a=["44901228","44901229"];S().C(a,ka,1);a=["44901218","44901217"];S().C(a,pa,2)}var re=function(){mc()!=N()&&ic(4)};
function se(){re();if(L?Rd(window)==1:!Rd(window))qe(),$d();var a=Nc(),b=a.r();b&&Fc().X(b,8);var c=k,b="";(c=window.google_async_iframe_id)?c=N().document.getElementById(c):(b="google_temp_span",c=te(b));var d=ee(c);c&&c.id==b&&Eb(c);d&&(b=ae(window,document,window.google_ad_url),a.b()&&a.v(String(window.google_ad_output||""),b,m,Rd(window)),de(window));qc(window)}
var ue=function(a){H(ld,function(b,c){a[b]=window[c]});H(kd,function(b,c){a[b]=window[c]});H(md,function(b,c){a[b]=window[c]})},ve=function(a){Vd(window.google_eids,1);a.eid=Ud();var b=Fc().ga();a.eid.length>0&&b.length>0&&(a.eid+=",");a.eid+=b};function we(){Bd()}
function xe(a){for(var b={},a=a.split("?"),a=a[a.length-1].split("&"),c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function ye(){var a=window,b=xe(document.URL);if(b.google_ad_override)a.google_ad_override=b.google_ad_override,a.google_adtest="on"}
function be(a,b,c){if(a&&(a=b.getElementById(a))&&c&&c.length!="")a.style.visibility="visible",a.innerHTML=c}
var he=function(a,b){var c;return c=J(a)?"/pagead/sdo?":b?"/pagead/render_iframe_ads.html#":"/pagead/ads?"},ze=function(a,b){b.dff=ed(a).toLowerCase();b.dfs=jd(a)},Ae=function(a,b){if(G.google_ad_output=="html")try{var c=$c(a,window.top);b.adx=Math.round(c.x);b.ady=Math.round(c.y)}catch(d){b.adx=-12245933,b.ady=-12245933}},Be=function(a){a.ref=window.google_referrer_url;a.loc=window.google_page_location;S().d(7)=="33895251"&&(a.aasl=Sd(N()))},fe=function(a){var b=zc(),c=Q(b,8),d=Q(b,9),e=window.google_ad_section;
if(J(window.google_ad_format)){if(R(b,4,Q(b,4)+1)>4&&!a)return m}else if(Sb(window)){if(R(b,5,Q(b,5)+1)>3&&!a)return m}else{var f=R(b,6,Q(b,6)+1);if(window.google_num_slots_to_rotate){if(ic(1),c[e]="",d[e]="",Q(b,12)||R(b,12,(new Date).getTime()%window.google_num_slots_to_rotate+1),Q(b,12)!=f)return m}else if(!a&&f>6&&e=="")return m}return i},ge=function(a){var b={};ue(b);le(b);Ub(b);a&&(ze(a,b),Ae(a,b));me(b);ne(b);ve(b);oe(b);Be(b);pe(b);b.fu=hc;return b},te=function(a){var b=window.google_container_id,
c=b&&sb(b)||sb(a);!c&&!b&&a&&(document.write("<span id="+a+"></span>"),c=sb(a));return c},ie=/[+, ]/;window.google_render_ad=se;var Ce=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");if(b==-1)return 0;else{var c=a.indexOf(";",b);return parseFloat(a.substring(b+5,c))}};var De=k,Ee=function(a){a.innerHTML=""},Fe=function(a,b,c,d,e,f){f=f||document;f=f.createElement("iframe");f.id=b;f.name=b;if(d!=k&&e!=k)f.width=String(d),f.height=String(e);f.vspace="0";f.hspace="0";f.allowTransparency="true";f.scrolling="no";f.marginWidth="0";f.marginHeight="0";f.frameBorder="0";f.style.border="0";if(c)f.style.visibility="hidden",f.style.display="none";a.appendChild(f);return f},Le=function(a,b,c){c=c||m;return Ce()!=0?Ge(a)?c?He(a,b):Ie(a,b):Je(a,b):Ke(a,b)},Ge=function(a){try{return!!a.contentWindow.document}catch(b){return m}},
Ke=function(a,b){try{var c=a.contentWindow?a.contentWindow.document:a.contentDocument;c.write(b);c.close()}catch(d){return Me("Could not write content into iframe using  the DOM standards method:"+d.message),m}return i},Je=function(a,b){var c=Ne();try{var d="google-ad-content-"+Ma();window[d]=b;var e='var adContent = window.parent["'+d+'"];window.parent["'+d+'"] = null;document.write(adContent);',e=Ce()==6?"window.onload = function() {document.write(\\'<sc\\' + \\'ript type=\"text/javascript\">document.domain = \""+
document.domain+'";'+e+"<\\/scr\\' + \\'ipt>\\');document.close(); };":'document.domain = "'+document.domain+'";'+e+"document.close();";a.src='javascript:\'<script type="text/javascript">'+e+"<\/script>'"}catch(f){return window[d]=k,Me("Could not write third party content into  IE iframe with modified document.domain: "+f.message),m}finally{Oe(c)}return i},He=function(a,b){var c=Ne();try{window.frames[a.name].contents=b,a.src=Pe(b)?'javascript:document.write(window["contents"]);document.close();':
'javascript:window["contents"]'}catch(d){return Me("Could not write third party content into IE iframe: "+d.message),m}finally{Oe(c)}return i},Ie=function(a,b,c){c=c||document;try{var d=a.contentWindow?a.contentWindow.document:a.contentDocument;if(d==k)if(c.implementation&&c.implementation.createDocument)d=c.implementation.createDocument("","doc_"+a.name,k);else if(typeof ActiveXObject!="undefined")d=new ActiveXObject("Msxml.DOMDocument");else return Me("Cannot create document in iframe "+a.name),
m;d.open("text/html","replace");d.write(b);d.close()}catch(e){return Me("Unable to write contents into IE iframe: "+e.message),m}return i},Me=function(a){De||(De=k);De.writeError(a)},Ne=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute("target");f&&(a.push({baseElement:e,originalTagValue:f}),e.removeAttribute("target"))}return a},Oe=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",
d.originalTagValue)}},Pe=function(a){var b="http://"+xa()+"/pagead/inject_object_div.js";return parseInt(Ce(),10)>6?m:a.indexOf(b)<0?m:i};var Qe={adsense_ad_client:"google_ad_client",adsense_adtest:"google_adtest",adsense_adsafe:"google_safe",adsense_cust_age:"google_cust_age",adsense_cust_gender:"google_cust_gender",adsense_host:"google_ad_host",adsense_host_tier_id:"google_ad_host_channel",adsense_language:"google_language",adsense_channel_ids:"google_ad_channel",adsense_host_channel_ids:"google_ad_host_tier_id",adsense_color_bg:"google_color_bg",adsense_color_border:"google_color_border",adsense_color_line:"google_color_line",adsense_color_link:"google_color_link",
adsense_color_text:"google_color_text",adsense_color_url:"google_color_url"},Re=0;function Se(){return i}t("googleCompanionsServicePresent",Se);function Te(){var a=[],b=Ue();if(b&&(b=b.getSlots()))for(var c=0,d=b.length;c<d;c++){var e=Ve(b[c]);a.push(e)}return a}t("googleGetCompanionAdSlots",Te);function Ve(a){var b={};if(a)b.slotId=a.getSlotId().getId(),b.adType=a.get("ad_type"),b.adSizes=We(a.getSizes());return b}
function We(a){var b=[];if(a&&p(a))for(var c=0,d=a.length;c<d;c++){var e={};e.adWidth=a[c].getWidth();e.adHeight=a[c].getHeight();b.push(e)}return b}function Xe(a,b){var c=Ue();if(c&&a&&p(a)){var d=c.getSlotIdMap();if(d)for(var e=0,f=a.length;e<f;e++){var g=a[e],j=g.slotId;j in d&&(j=d[j],g.adContent?g.friendlyIframeRendering?Ye(j,g.adContent,g.adWidth,g.adHeight):c.fillSlot(j,g.adContent):j.get("backfill")&&Ze(j,b))}}}t("googleSetCompanionAdContents",Xe);
function Ye(a,b,c,d){var e=rb(a.getSlotId().getDomId());e&&(Ee(e),a=Fe(e,"google_companion_"+a.getSlotId().getId(),m,c?c:a.getSizes()[0].getWidth(),d?d:a.getSizes()[0].getHeight()),Le(a,b,i))}
function Ze(a,b){Bd();var c=G;c.google_container_id=a.getSlotId().getDomId();c.google_ad_type="image";c.google_ad_output="html";if(a){var d=a.getSizes();if(p(d)&&d.length>0){var e=d[0].getWidth(),d=d[0].getHeight();c.google_ad_width=e;c.google_ad_height=d;c.google_ad_format=e+"x"+d+"_as"}}H(Qe,function(d,e){var j=a.get(e);j?c[d]=j:b&&(c[d]=b[e])});se()}function Ue(){return typeof googletag!="undefined"&&googletag&&typeof googletag.companionAds=="function"?googletag.companionAds():k}
function $e(a){var b=window,c=document;if(b.google_container_id)a?(b=c.getElementById(b.google_container_id),b.innerHTML=a,b.style.visibility="visible"):se()}t("google_show_companion_ad",$e);function af(a,b){if(a&&b){var c=document.getElementById(a);c.innerHTML=b;c.style.visibility="visible"}}t("google_show_companion_ad_in_slot",af);
function bf(){var a={},b=window;if(b.google_container_id)a.adType=b.google_ad_type,a.adHeight=b.google_ad_height,a.adWidth=b.google_ad_width,a.adContainerId=b.google_container_id;return a}t("google_get_companion_slot_params",bf);function cf(a){a&&(a+="&label=elementview&value=0",Pb(G,a))}t("google_companion_error",cf);function df(a){if(a){var b=ef(),b=a+"&label=elementview&value="+b;Pb(G,b);ff()&&gf()&&hf(a)}}t("google_companion_loaded",df);function jf(){Re++}
t("google_increment_num_ad_mouseovers",jf);function ef(){var a=F,b=G,b=a.getElementById(b.google_container_id);if(!b)return 3;if(kf(b))return 4;if(lf(b))return 5;if(!gf())return 7;a=cd(b).ta();b=Yc(b);return Qc(b,a)?1:b.left<=a.right&&a.left<=b.right&&b.top<=a.bottom&&a.top<=b.bottom?2:6}function gf(){var a=F,b=G;if(a=a.getElementById(b.google_container_id)){a=a.childNodes;for(b=0;b<a.length;b++)if(a[b].id=="aw0")return a[b].href}return""}
function ff(){var a=F,b=G;return(a=a.getElementById(b.google_container_id))?!kf(a)&&!lf(a):m}function hf(a){var b=gf(),c=a+"&label=overlayadclose",d=0,e=0,a=function(){if(e!=0&&(d+=5E3,d>=18E5||!ff()||b!=gf())){clearInterval(e);var a=c+"&value=";a+=d>=18E5?4:ff()?gf()?2:3:1;Re>0&&(a+=";numOfMouseOvers="+Re,Re=0);Pb(G,a)}},e=setInterval(a,5E3)}
function kf(a){for(;a;){if(a.style)if(a.style.visibility=="hidden"||a.style.visibility=="collapse")return i;else if(a.style.visibility=="visible")break;a=a.parentNode}return m}function lf(a){for(;a;){if(a.style&&a.style.display=="none")return i;a=a.parentNode}return m}function mf(){var a=Ue();if(a&&a.onImplementationLoaded)a.onImplementationLoaded()}mf();function nf(){ye();we()}ec("show_companion_ads.main",gc,nf);})()


}
/*
     FILE ARCHIVED ON 12:50:50 Oct 27, 2011 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 02:12:36 Oct 10, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.623
  exclusion.robots: 0.018
  exclusion.robots.policy: 0.008
  esindex: 0.013
  cdx.remote: 13.135
  LoadShardBlock: 262.31 (6)
  PetaboxLoader3.datanode: 198.933 (7)
  load_resource: 967.173
  PetaboxLoader3.resolve: 880.253
*/