(function(g){var window=this;'use strict';var G3=function(a){a.publish("cardstatechange",a.Hk()&&a.fp()?1:0)},H3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},gob=function(a){var b=g.Is(a);
a=g.Ls(a);return new g.ws(b.x,b.y,a.width,a.height)},hob=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.VB(a,b,function(){g.WB(e);c.apply(a,arguments)},d)},K3=function(a){a=g.fb(a);
delete I3[a];g.id(I3)&&J3&&J3.stop()},job=function(){J3||(J3=new g.kv(function(){iob()},20));
var a=J3;a.isActive()||a.start()},iob=function(){var a=g.kb();
g.Vc(I3,function(b){kob(b,a)});
g.id(I3)||job()},L3=function(a,b,c,d){g.yv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},kob=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;lob(a,a.progress);1==a.progress?(a.j=0,K3(a),a.onFinish(),a.Dr()):a.isPlaying()&&a.iM()},lob=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},mob=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},M3=function(a,b,c,d,e){L3.call(this,b,c,d,e);
this.element=a},nob=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
M3.call(this,a,b,c,d,e)},oob=function(a){return Math.pow(a,3)},pob=function(a){return 3*a*a-2*a*a*a},qob=function(a){g.I.call(this);
this.B=a||window;this.j=[]},N3=function(a){return a.baseUrl||null},O3=function(a,b){return g.Ht(g.Rr(a,b),function(c){return!!c})},rob=function(a,b,c){function d(ka){var ia=ka.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var sa=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var U=f(ia.subscriberCountWithUnsubscribeText);var Ja=f(ia.subscriberCountText)}else U=f(ia.subscriberCountText),Ja=f(ia.subscriberCountWithSubscribeText);var x=null;if(ka.signinEndpoint){x=H3(ka,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,Ka;x=null==(Ka=g.V(null==(ba=ia.signInEndpoint)?void 0:ba.commandMetadata,g.z2))?void 0:
Ka.url}if(!x)return null}return sa&&(aa||x)?{subscribed:ia.subscribed,subscribeText:sa,subscribeCount:U,unsubscribeText:aa,unsubscribeCount:Ja,enabled:ia.enabled,signinUrl:x,classic:ka.useClassicSubscribeButton}:null}
function e(ka){if(ka){var ia=[],sa=ka.videoId;sa&&ia.push("v="+sa);(sa=ka.playlistId)&&ia.push("list="+sa);(ka=ka.startTimeSeconds)&&ia.push("t="+ka);return"/watch?"+ia.join("&")}}
function f(ka){if(!ka)return null;var ia=ka.simpleText;return ia?ia:ka.runs?g.Rr(ka.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,C=null,F=null,H=null,L=null,M=null;if("VIDEO"===h)g.V(l,g.EF)?m=g.V(l,g.EF).url:(M=g.V(l,g.SS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.V(l,g.EF)?m=g.V(l,g.EF).url:(M=g.V(l,g.SS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=H3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((F=H3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=H3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=H3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ea="";if(b.metadata){var na=f(b.metadata);na&&(ea=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ea,callToAction:f(b.callToAction),QW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,zE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,Z8:n,sessionData:R?{itct:R}:null,tda:q,XC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:O3(b.impressionUrls||[],N3),M8:O3(b.hovercardShowUrls||[],N3),clickUrls:O3(l.loggingUrls||[],N3),visualElement:g.KE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},sob=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O3(a.impressionUrls||[],N3),elements:O3(a.elements||[],function(d,e){return rob(b,d,e)})};
a.trackingParams&&(c.visualElement=g.KE(a.trackingParams));return c},tob=function(a){g.sV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.JR(a)||g.LR(a);this.events=new g.jK(this);g.N(this,this.events);this.events.T(this.player,g.rJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.sJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.hc);this.events.T(window,"focus",this.Fba);this.load();var b=g.yf("STYLE");(g.lf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Ff(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},uob=function(a){return a.player.getVideoData().Jf?"current":a.Z?"new":"current"},P3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},vob=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=sob(f,uob(a))));Q3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.wy;d&&(c.postParams={ad_tracking:d});if(b=g.dWa(b))if(b=g.fe(b),b=g.$d(b))a.C=g.lB(b,c)},Q3=function(a,b,c){c=void 0===c?!0:c;
a.player.sf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&wob(a);c=[];d=new g.qJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.ZT(a.player,a.B.element,4),a.D=new g.SF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=xob(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.ZT(a.player,f.element,4);var h=new g.qJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);yob(a,f,e)}else g.QE(new g.lC("buildEndscreenElement null",
e))}a.player.lf(c);a.hc()}},wob=function(a){var b=g.LE(),c=g.ME();
c&&b&&a.endscreen.visualElement&&g.SA(g.YE)(void 0,c,b,a.endscreen.visualElement)},xob=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.XC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:R3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:S3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:b.zE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.XC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:R3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:S3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.XC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Cv(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:R3(b)}]};c=new g.W(c);var d=g.mf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.tv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.bW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.XC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:R3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:zob(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.XC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Cv(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:S3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:R3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.tv(c.element,"ytp-ce-placeholder");return c},R3=function(a){if(a.QW)var b=a.QW.thumbnails;
return zob(b?b[b.length-1].url:null)},zob=function(a){return a?{style:"background-image: url("+a+")"}:{}},yob=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.tv(b.element,"ytp-ce-force-expand"),T3(a,c.id,!0)):(g.vv(b.element,"ytp-ce-force-expand"),g.vv(b.element,"ytp-ce-element-hover"),T3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Aob(a,b,c)});
b.listen("mouseleave",function(){Bob(a,b,c)});
a.player.U().B||b.listen("click",function(){g.tv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Cob(a,c,m)});
b.listen("keypress",function(m){Cob(a,c,m)});
b.listen("focus",function(){Aob(a,b,c)});
b.listen("blur",function(){Bob(a,b,c)});
b.listen("touchstart",function(){Aob(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.vv(b.element,"ytp-ce-element-hover");g.vv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Cob=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.rv(d,"ytp-ce-element");){g.rv(d,"subscribe-label")&&Dob(a,b);
if(g.rv(d,"ytp-ce-channel-subscribe"))return;d=g.Gf(d)}if(!d||g.rv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Bob(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.tda)Dob(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.fe(S3(a,b.targetUrl)),c=g.$d(c),g.yG(c,void 0,b.sessionData);else{var e=g.UR(a.player.U())||a.player.getVideoData().Jf,f=function(){var h=S3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.XA(h);e&&n&&
(n.v||n.list)?a.player.Mo(n.v,l,n.list,!1,void 0,m||void 0):g.mya(h,l)};
Dob(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.bS(a)+b}else return"";return b},Aob=function(a,b,c){g.rv(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.tv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.kv(function(){g.tv(b.element,"ytp-ce-element-hover")},200)).start():g.tv(b.element,"ytp-ce-element-hover"),U3(a,c.M8),T3(a,c.id,!0))},Bob=function(a,b,c){g.vv(b.element,"ytp-ce-element-hover");
g.vv(b.element,"ytp-ce-force-expand");T3(a,c.id,!1)},T3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.xv(a.j[e].element,"ytp-ce-element-shadow-show",c)},U3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P3(a))c&&c();else{b=Eob(a,b);var e=0,f=!1,h=new g.kv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.FD(b[a],d)}},Dob=function(a,b,c){U3(a,b.clickUrls,c);
(a=g.ME())&&b.Z8&&g.eF(a,b.visualElement)},Eob=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Fob(b[d],c));return a},Fob=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Gob=function(a){return"string"===typeof a?a:""},V3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Hob=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W3=function(a){return a.value?a.value:null},X3=function(a){if(!a)return null;
var b=g.fe(Gob(a.value));b=g.$d(b);if(!b)return null;var c=V3(a.target,Iob,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Hob(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Job=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Mob=function(a){if(!a)return null;
var b=V3(a.type,Kob),c=V3(a.trigger,Lob);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X3(a?a:null);return b?new Job(b,c,a):null},Nob=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Oob=function(a,b){return g.Db(a.action,b)},Pob=function(a,b){this.context=a;
this.j=b},Qob=function(a){return a.customMessage?Y3("div","iv-card-message",a.customMessage):""},Z3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Rob=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},Y3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Cv(c);return{I:a,X:b,xa:c}},Sob=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.iD&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.iD+");");c.dir=g.Cv(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},$3=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.cj.click,5)}},Tob=function(a,b){this.merchant=a;
this.price=b},Uob=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Vob=function(a,b){return b?b:Uob(a)?"current":"new"},a4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Wa=new Map;this.Za=new Map;this.context.J.addEventListener(g.rJ("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.sJ("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},b4=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.jM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},Wob=function(a){var b;
return(null==(b=g.V(a,g.EF))?0:b.url)?g.V(a,g.EF).url:(a=g.V(a,g.SS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c4=function(a,b,c){return{nY:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
U0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
yL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Xob=function(a,b,c){a4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Gb=this.Ma=this.Jb=this.C=this.isInitialized=!1;this.cards=[];this.zb=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Gf=this.Ga=null;this.K=0;this.Fa=new g.kv(function(){},c.W.Gl?4E3:3E3);
g.N(this,this.Fa);this.eb=new g.kv(function(){});
g.N(this,this.eb);this.Ca=new Pob(c,function(e,f,h,l,m,n){b4(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.bb=new g.SF(this.Y,330);g.N(this,this.bb);this.Hb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Jb&&d4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Jb=d.C)&&e4(d)});
this.Ra=new g.jK(this);g.N(this,this.Ra);this.J.addEventListener("videodatachange",this.vt.bind(this))},Yob=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e4(a)});
var c=b.headerText;g.Of(a.Hb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.KE(b.trackingParams);a.N=g.KE(b.closeTrackingParams);a.Gf=g.KE(b.iconTrackingParams)},Zob=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.sF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,cj:{},ip:null,Hj:e.trackingParams?g.KE(e.trackingParams):null,Gf:f&&f.trackingParams?g.KE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
iD:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.sF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:g4(a,c,b,f),sponsored:!1,cj:c4(f,e,f.command),ip:f.trackingParams?g.KE(f.trackingParams):null,Hj:e.trackingParams?g.KE(e.trackingParams):null,Gf:l&&l.trackingParams?g.KE(l.trackingParams):null,imageUrl:h4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.sF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,iD:null,title:f.title?g.sF(f.title):"",customMessage:f.callToAction?g.sF(f.callToAction):"",url:g.V(f.command,g.EF).url?X3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.EF).url}):null,onClickCommand:null};f4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.sF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,cj:c4(e,f,e.endpoint),ip:e.trackingParams?g.KE(e.trackingParams):null,Hj:f.trackingParams?g.KE(f.trackingParams):null,Gf:l&&l.trackingParams?g.KE(l.trackingParams):null,channelId:g.V(e.endpoint,g.gT).browseId,customMessage:e.customText?g.sF(e.customText):null,profileImageUrl:h4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.sF(e.channelName):"",metaInfo:[e.subscriberCountText?g.sF(e.subscriberCountText):""],url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.gT).canonicalBaseUrl?g.V(e.endpoint,g.gT).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.gT).browseId}),onClickCommand:null};f4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.sF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,cj:c4(e,f,e.action),ip:e.trackingParams?g.KE(e.trackingParams):null,Hj:f.trackingParams?g.KE(f.trackingParams):null,Gf:l&&l.trackingParams?g.KE(l.trackingParams):null,NG:h4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.sF(e.customMessage):null,playlistVideoCount:g.sF(e.playlistVideoCount),title:e.playlistTitle?g.sF(e.playlistTitle):"",metaInfo:[e.channelName?g.sF(e.channelName):
"",e.videoCountText?g.sF(e.videoCountText):""],url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Wob(e.action)}),onClickCommand:null};f4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.sF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g4(a,c,b,e),sponsored:!1,cj:c4(e,f,e.action),ip:e.trackingParams?g.KE(e.trackingParams):null,Hj:f.trackingParams?g.KE(f.trackingParams):null,Gf:l&&l.trackingParams?g.KE(l.trackingParams):null,NG:h4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.sF(e.lengthString):null,customMessage:e.customMessage?g.sF(e.customMessage):null,title:e.videoTitle?g.sF(e.videoTitle):"",metaInfo:[e.channelName?g.sF(e.channelName):
"",e.viewCountText?g.sF(e.viewCountText):""],isLiveNow:!!e.badge,url:X3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Wob(e.action)}),onClickCommand:null};f4(a,b)}}}}}a.K++},h4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},g4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},apb=function(a,b){if(b=$ob(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Bf.id),g.Ff(b.AN),g.Hb(a.cards,b),a.RH(),i4(a)},d4=function(a,b,c){if(!a.C){a.bb.show();
a.Va=new g.kv(function(){g.tv(a.context.J.getRootNode(),g.KY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ra.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.ME();d&&a.Ga&&a.N&&g.cF(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.gZ||(f.gZ=!0,bpb(a.context.logger,f.Bf.cj.nY,b)),d&&g.cF(d,[f.Bf.ip]);G3(a.J);c&&(a.G=new g.kv(function(){a.La=a.Z;a.zb.focus()},330),a.G.start())}},e4=function(a){a.C&&(a.bb.hide(),g.aC(a.Ra),g.vv(a.context.J.getRootNode(),g.KY.IV_DRAWER_OPEN),a.C=!1,G3(a.J),a.G&&a.G.stop(),a.G=new g.kv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},dpb=function(a){g.uv(a.Ib(),
[g.KY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ZT(a.J,a.D,5);cpb(a);a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.zb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},cpb=function(a){var b=g.tf("iv-drawer-close-button",a.D);
a.context.j.listen(b,"click",a.w6,a);a.context.j.listen(a.B,"touchend",function(){a.Fa.start()});
a.context.j.listen(a.B,"scroll",a.T6,a);a.context.B.subscribe("onHideControls",function(){a.Ma=!0});
a.context.B.subscribe("onShowControls",function(){a.Ma=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Ma=g.rv(a.J.getRootNode(),"ytp-autohide")});
a.qa.push(g.TD("iv-button-shown",a.r9,a));a.qa.push(g.TD("iv-button-hidden",a.q9,a));epb(a)},epb=function(a){a.qa.push(g.TD("iv-teaser-shown",a.B3,a));
a.qa.push(g.TD("iv-teaser-hidden",a.s9,a));a.qa.push(g.TD("iv-teaser-clicked",a.A3,a));a.Gb=!0},fpb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.V(b.onClickCommand,g.Ikb))?void 0:c.targetId)?(a.ra=b,!0):!1},gpb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.DUa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.V(h[0],g.Z1a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},f4=function(a,b){if(!fpb(a,b)||gpb(a,b)){var c=hpb(a,b);
if(c){var d={Bf:b,AN:c.element,gZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Gb||epb(a),apb(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||dpb(a);apb(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.RH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,i4(a),ipb(a,d),d4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&jpb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){jpb(a,d)}),i4(a))}}},hpb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Sob(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?W3(b.url)||"":""},V:[Z3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[Y3("h2",void 0,b.title),d]}]}]};c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:W3(b.url)||"","data-ytid":b.channelId},V:[Z3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Qob(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Rob(b)]}]}]};c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:W3(b.url)||""},V:[Z3(b.NG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Qob(b),Y3("h2","iv-card-primary-link",b.title),Rob(b)]}]}]};
c=new g.W(c);$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Sob(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?W3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[Y3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Of(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Md(d,"adInfo");$3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:W3(c))||""},V:[Z3(b.NG,d),{I:"div",S:"iv-card-content",V:[Qob(b),Y3("h2","iv-card-primary-link",b.title),Rob(b),f]}]}]};c=new g.W(e);$3(a,g.sf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},kpb=function(a){if(a.j)return"productListing"===a.j.Bf.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Sr(a.cards,function(c){return"productListing"===c.Bf.type})}return g.Sr(a.cards,function(c){return"productListing"===c.Bf.type})},i4=function(a){g.xv(a.J.getRootNode(),"ytp-cards-shopping-active",kpb(a))},jpb=function(a,b){if(!g.rv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.ME(),d=a.j?a.j.Bf.Gf:a.Gf;
c&&d&&g.dF(c,[d]);a.j=b;i4(a)}(c=a.isInitialized&&"none"==a.Ib().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.Bf.teaserDurationMs&&a.J.AB(!0,{teaserText:b.Bf.teaserText,durationMs:b.Bf.teaserDurationMs,onClickCommand:b.Bf.onClickCommand});a.eb.isActive()||((!a.C||!a.Fa.isActive()&&a.Ma)&&ipb(a,b),a.eb.start(910+b.Bf.teaserDurationMs))}},ipb=function(a,b){a.Y.Eb?(b=new L3([0,
a.B.scrollTop],[0,b.AN.offsetTop],600,pob),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.oF(a.Y,!0),a.B.scrollTop=b.AN.offsetTop,g.oF(a.Y,!1))},j4=function(a){return a.j&&a.j.Bf?a.j.Bf:a.cards[0]&&a.cards[0].Bf?a.cards[0].Bf:null},$ob=function(a,b){return g.Db(a.cards,function(c){return c.Bf.id===b})},k4=function(a,b,c){a4.call(this,a,b);
this.annotation=c;this.isActive=!1},lpb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l4=function(a,b,c){k4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},mpb=function(a,b){var c=void 0===c?0:c;
var d=gob(b).width;g.Gs(b,d);c=new nob(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,oob);g.N(a,c);a.context.C.listen(c,"begin",function(){g.Ms(b,!0)});
c.play()},ppb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.bW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Ms(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.zs(l,"right",b.image_width+"px");g.Af(a.Ib(),l);a.C=new g.kv(function(){npb(a,h,l)},500);
g.N(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){opb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},opb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Ls(b);a.j||(b.style.width=g.Fs(f.width,!0),c.style.width=g.Fs(f.width,!0));g.zs(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zs(d,"right","1px");a.D=!0;g.Ms(b,!0);a.G=new g.kv(function(){g.tv(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},npb=function(a,b,c){g.vv(a.Ib(),"iv-branding-active");
a.K=new g.kv(function(){g.Ms(b,!1);a.j||(c.style.width=g.Fs(0,!0))},250);
a.K.start();a.D=!1},qpb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},rpb=function(a,b,c){k4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.kv(function(){d.j.setAttribute("aria-hidden","true");g.Ms(d.C,!1);g.Ms(d.B,!0)},700,this);
g.N(this,this.G)},upb=function(a,b,c){c.stopPropagation();
spb(a);tpb(a,b);a.j.focus()},vpb=function(a){a.isCollapsed||a.Z||a.D||(g.tv(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},spb=function(a){a.G.stop();
a.isCollapsed&&(g.wv(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ms(a.B,!1),g.Ms(a.C,!0))},tpb=function(a,b){a.D||(a.D=g.Bg(function(){wpb(this);
vpb(this)},b,a))},wpb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},xpb=function(a){this.J=a},bpb=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.Wu(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.FD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},ypb=function(a){g.sV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new xpb(this.player);this.D=new g.jK(this);this.G=this.N=null;this.events=new g.jK(this);this.Tg=this.Y=this.j=null;this.ra=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.C3,this);this.subscribe("resize",this.qK,this);this.player.U().Ma.subscribe("vast_info_card_add",this.l_,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.ZT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.vu()&&this.load();var c=this.createElement({I:"style"});(g.lf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Ff(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},zpb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Ms(a,!1);return a},Apb=function(a,b){b=!b.isCued()&&!g.YF(b,1024);
g.oF(a.B,b);g.oF(a.C,b)},Bpb=function(a,b,c){a.Z=!0;
a.G=g.lB(b,c)},Cpb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Cpb(a,e))}return c},Gpb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.eB(h)&&h.responseXML?h.responseXML:null)&&Dpb(a,h)}};
g.tC()&&(d.onFinish=Epb(a,d.onFinish));d.postParams={ic_only:"1"};Fpb(d,c);a.Z=!0;g.lB(b.Va,d)}}},Fpb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.WH&&(a.postParams.ic_coll=b.WH);b.BN&&(a.postParams.ic_xml=b.BN);b.DL&&(a.postParams.ic_track=b.DL)},Hpb=function(a){var b=new g.W({I:"div"});
g.Ms(b.element,!1);var c=new Xob(a.player,b.element,n4(a));g.N(c,b);b.Ja(a.B.element);c.wG();return c},Jpb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.qa=!0,Ipb(a,b),b.headerText&&a.Tg&&(c=g.sF(b.headerText),a.Tg.setAttribute("title",c))},n4=function(a){if(!a.Y){var b=new qob(a);
g.N(a,b);var c=new g.Kp(a);g.N(a,c);a.Y=new qpb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.rj)}return a.Y},Dpb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ME();if(e){var f=g.LE();f&&g.SA(g.Lwa)(void 0,e,f,[g.KE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Cpb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=V3(f.type,Kpb),p=V3(f.style,Lpb),q=Gob(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Mob;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Nob(m,n,p,v,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=zpb(f),L=null;switch(l.type){case "branding":if(f.player.U().Td)break;f.B.element.appendChild(H);L=new l4(H,n4(f),l);break;case "promotion":g.ZT(f.player,H,4),L=new rpb(H,n4(f),l)}L&&L.wG();if(f=L)g.N(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Hpb(a),g.N(a,a.j));if("card"===e.type){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={nY:f.impression,click:f.click,close:f.close,U0:f.teaser_impression,yL:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,ip:l.card?g.KE(l.card):null,Hj:l.teaser?g.KE(l.teaser):null,Gf:l.icon?g.KE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,
ip:l.card?g.KE(l.card):null,Hj:l.teaser?g.KE(l.teaser):null,Gf:l.icon?g.KE(l.icon):null,NG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "productListing":e.signin_url&&(L=X3({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],ea=0;ea<R.length;ea++)M.push(new Tob(g.Ye(R[ea].merchant),
g.Ye(R[ea].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,ip:l.card?g.KE(l.card):null,Hj:l.teaser?g.KE(l.teaser):null,Gf:l.icon?g.KE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,iD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),oqb:L,nqb:e.signin_title?e.signin_title:void 0,mqb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};f4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,ip:l.card?g.KE(l.card):
null,Hj:l.teaser?g.KE(l.teaser):null,Gf:l.icon?g.KE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,iD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};f4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,cj:f,ip:l.card?g.KE(l.card):null,Hj:l.teaser?g.KE(l.teaser):null,Gf:l.icon?g.KE(l.icon):null,NG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:X3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},f4(H,c)}}else Yob(a.j,e);c=!0}}c&&
(G3(a.player),a.qK())},Ipb=function(a,b){var c=!1;
a.j||(a.j=Hpb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Zob(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.nT(f)||(c=a.j,d=b.headerText?g.sF(b.headerText):"",g.Of(c.Hb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.KE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.KE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Gf=b.icon.infoCardIconRenderer.trackingParams?g.KE(b.icon.infoCardIconRenderer.trackingParams):null,a.qK());G3(a.player)}},Mpb=function(a,b,c,d,e){if(!a.player.U().Td){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.gT)&&g.V(b.navigationEndpoint,g.gT).browseId&&f.push(new Job("openUrl","click",new Hob("/channel/"+g.V(b.navigationEndpoint,g.gT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.hT)){d.channel_id=g.V(b.subscribeButton,g.hT).channelId;var l;b=g.V(b.subscribeButton,g.hT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.sF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.sF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.sF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.sF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.V(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.z2))?void 0:m.url)||"";l={subscribeText:g.sF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.sF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Nob(c,"branding","branding",f,d);l=zpb(a);a.B.element.appendChild(l);f=new l4(l,n4(a),f);f.wG();g.N(f,f);a.K[c]=f}},Epb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.Na()||a.ra.push(g.Zu.Pi(function(){b.apply(null,g.qa(c))}))}},Npb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.RT.prototype.AB=g.fa(28,function(a,b){var c=g.KV(this.yb());c&&c.AB(a,b)});
var I3={},J3=null;g.lb(L3,g.yv);g.k=L3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;K3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.hK();this.vn("play");this.isPaused()&&this.vn("resume");this.j=1;var b=g.fb(this);b in I3||(I3[b]=this);job();kob(this,a);return!0};
g.k.stop=function(a){K3(this);this.j=0;a&&(this.progress=1);lob(this,this.progress);this.onStop();this.Dr()};
g.k.pause=function(){this.isPlaying()&&(K3(this),this.j=-1,this.vn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.vn("destroy");L3.Of.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.iM=function(){this.vn("animate")};
g.k.vn=function(a){this.dispatchEvent(new mob(a,this))};
g.lb(mob,g.zb);g.lb(M3,L3);M3.prototype.C=function(){};
M3.prototype.iM=function(){this.C();M3.Of.iM.call(this)};
M3.prototype.Dr=function(){this.C();M3.Of.Dr.call(this)};
M3.prototype.hK=function(){this.C();M3.Of.hK.call(this)};
g.lb(nob,M3);nob.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(qob,g.I);g.k=qob.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.VB(a,b,c);this.j.push(a);return a};
g.k.SE=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=hob(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.WB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.WB(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.y(tob,g.sV);g.k=tob.prototype;g.k.load=function(){g.sV.prototype.load.call(this);if(!P3(this)){var a=g.eWa(this.player.getVideoData());a?(a=sob(a,uob(this)),Q3(this,a,!1)):vob(this)}};
g.k.unload=function(){Q3(this,null);this.C&&(this.C.abort(),this.C=null);g.sV.prototype.unload.call(this)};
g.k.Sh=function(a,b){return P3(this)?"loadCustomEndscreenRenderer"===a?(a=sob(b,"new"),Q3(this,a),!0):null:null};
g.k.getOptions=function(){return P3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.hc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Opb.length;f++){var h=Math.abs(b.width-Opb[f]);if(-1===e||d>=h)e=f,d=h}d=Ppb[e];this.B&&g.zs(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ks(e.element,m,f);g.Gs(e.element,n,p);g.wv(e.element,Qpb);256<m||256<f?g.tv(e.element,"ytp-ce-large-round"):96<m||96<f?g.tv(e.element,"ytp-ce-medium-round"):g.tv(e.element,"ytp-ce-small-round");g.wv(e.element,Rpb);m=h.left+h.width/2;h=h.top+l/2;g.tv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.wv(e.element,Ppb);g.tv(e.element,d);(e=g.mf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zs(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())U3(this,this.endscreen.impressionUrls),(a=g.ME())&&this.endscreen.visualElement&&g.bF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.tv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.tv(b,"ytp-ce-shown");U3(this,c.impressionUrls);(b=g.ME())&&g.bF(b,c.visualElement);this.player.U().N&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.vv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.vv(b,"ytp-ce-shown");this.player.U().N&&this.player.jb("endscreenelementhidden",a)}};
g.k.Fba=function(a){var b=this;a.target===window&&(new g.kv(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.wv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Opb=[346,426,470,506,570,640,853,1280,1920],Ppb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Rpb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Qpb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Iob={uva:"current",DWa:"new"};var Kob={CLOSE:"close",u_a:"openUrl",SUBSCRIBE:"subscribe"},Lob={Cta:"click",CLOSE:"close",xHa:"hidden",y5a:"rollOut",z5a:"rollOver",q7a:"shown"};Nob.prototype.Me=function(){var a=Oob(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Lpb={Vna:"anchored",B2:"branding",CHANNEL:"channel",jva:"cta",AHa:"highlightText",ELa:"label",PLAYLIST:"playlist",POPUP:"popup",s$a:"speech",SUBSCRIBE:"subscribe",idb:"title",VIDEO:"video",Lkb:"website"},Kpb={B2:"branding",gra:"card",uxa:"drawer",zHa:"highlight",URa:"marker",J3a:"promotion",TEXT:"text",vmb:"widget"};g.y(a4,g.I);g.k=a4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.qJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.Za.set(a,e);this.context.J.lf([a])};
g.k.wG=function(){this.context.B.subscribe("resize",this.RH,this)};
g.k.Ib=function(){return this.element};
g.k.jM=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ff(this.Ib())};
g.k.RH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W3(a);if(f){var h=Vob(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Jf||!1,n=g.XA(f||"");m&&n&&(n.v||n.list)?e.context.J.Mo(n.v,b,n.list,!1):g.yG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);Uob(f)||(c=g.ME(),d=b.itct,c&&d&&g.eF(c,g.KE(d)))}};
g.k.va=function(){this.Wa.clear();this.Za.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.y(Xob,a4);g.k=Xob.prototype;g.k.vt=function(){this.ra&&f4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Ls(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.RH=function(){var a=this.isAvailable();g.Ms(this.Ib(),a);g.xv(this.context.J.getRootNode(),g.KY.IV_DRAWER_ENABLED,a);G3(this.J)};
g.k.destroy=function(){this.J.AB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.UD(this.qa);g.aC(this.Ra);this.Va&&this.Va.dispose();this.G&&this.G.dispose();a4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.Bf.startMs>c.Bf.startMs||a.Bf.startMs===c.Bf.startMs&&a.Bf.timestamp>=c.Bf.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.w6=function(){if(this.C){m4(this.context.logger,j4(this).cj.close);var a=g.ME();a&&this.N&&g.eF(a,this.N);e4(this)}};
g.k.T6=function(){g.xv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.r9=function(){var a=g.ME(),b=j4(this);b=b?b.Gf:this.Gf;a&&b&&g.cF(a,[b])};
g.k.q9=function(){var a=g.ME(),b=j4(this);b=b?b.Gf:this.Gf;a&&b&&g.dF(a,[b])};
g.k.B3=function(){var a=j4(this);m4(this.context.logger,a.cj.U0);var b=g.ME();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Hj&&c.push(a.Hj);a.Gf&&c.push(a.Gf);0<c.length&&g.cF(b,c)}else g.cF(b,[a.Hj,a.Gf])};
g.k.s9=function(){var a=g.ME(),b=j4(this);a&&b&&g.dF(a,[b.Hj])};
g.k.A3=function(a){var b=j4(this),c=g.ME();this.j?a?(a=this.context.logger,m4(a,b.cj.yL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hj&&g.eF(c,b.Hj)):(a=this.context.logger,m4(a,b.cj.yL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gf&&g.eF(c,b.Gf)):(a=this.context.logger,m4(a,b.cj.yL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Gf&&g.eF(c,this.Gf))};g.y(k4,a4);k4.prototype.wG=function(){a4.prototype.wG.call(this);lpb(this)};
k4.prototype.show=function(){a4.prototype.show.call(this);var a=g.ME(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.cF(a,[g.KE(b.itct)])};
k4.prototype.hide=function(){a4.prototype.hide.call(this);var a=g.ME(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.dF(a,[g.KE(b.itct)])};g.y(l4,k4);l4.prototype.Bx=function(){g.tv(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ms(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Me();c&&b4(this,b,c,this.annotation.id,a.session_data);ppb(this,a)};
l4.prototype.show=function(){if(!this.isActive&&(k4.prototype.show.call(this),this.N||(this.Bx(),this.N=!0),g.Ms(this.Ib(),!0),this.isActive=!0,this.B)){try{mpb(this,this.B)}catch(a){}g.tv(this.context.J.getRootNode(),"ytp-branding-shown")}};
l4.prototype.hide=function(){this.isActive&&(k4.prototype.hide.call(this),g.Ms(this.Ib(),!1),this.isActive=!1,g.vv(this.context.J.getRootNode(),"ytp-branding-shown"))};
l4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k4.prototype.destroy.call(this)};g.y(rpb,k4);g.k=rpb.prototype;
g.k.Bx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Me(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&b4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Ke(f,W3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&b4(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.tv(this.j,"iv-click-target");e&&b4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.tv(this.j,"iv-click-target"),e&&b4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){upb(a,5E3,q)});
c.appendChild(this.B);g.Ms(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.n8,this);this.context.j.listen(this.Ib(),"mouseout",this.m8,this);this.context.j.listen(this.Ib(),"touchend",function(q){upb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.i8:this.h8,this);c.appendChild(this.C);g.uv(this.Ib(),d);h&&(g.Af(this.Ib(),h),n&&h.appendChild(n));g.Af(this.Ib(),this.N);g.Af(this.Ib(),c)};
g.k.show=function(){this.isActive||(k4.prototype.show.call(this),this.Y||(this.Bx(),this.Y=!0),g.Ms(this.Ib(),!0),g.Bg(function(){g.vv(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,wpb(this),spb(this),tpb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.tv(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.jM=function(a,b,c,d,e,f){return this.isCollapsed?!1:k4.prototype.jM.call(this,a,b,c,d,e,f)};
g.k.n8=function(a){this.Z=!0;upb(this,500,a)};
g.k.m8=function(){this.Z=!1;vpb(this)};
g.k.h8=function(a){a.stopPropagation();this.hide()};
g.k.i8=function(a){a.stopPropagation();wpb(this);this.isCollapsed=!0;g.tv(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();k4.prototype.destroy.call(this)};g.y(ypb,g.sV);g.k=ypb.prototype;g.k.Sh=function(a,b){if(!Npb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.e2(b))&&Dpb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(apb(this.j,b),G3(this.player)),!0}return null};
g.k.getOptions=function(){return Npb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.vu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.zT(b)||g.KT(this.player.app)?!1:1===c&&!b.pW||a.Ma.get(b.videoId)||g.oT(b)||g.fWa(b)?!0:!1};
g.k.qK=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ks(this.C.element,a.width,a.height);g.Gs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Fn();a=this.j;b=b.width;g.xv(a.D,"iv-drawer-small",426>=b);g.xv(a.D,"iv-drawer-big",1280<=b)}};
g.k.C3=function(a){Apb(this,a.state);g.YF(a.state,2)&&(this.Hk()&&this.fp()&&2!==this.player.getPresentingPlayerType()&&this.BB(!1),this.AB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.eB(h)&&h.responseXML?h.responseXML:null)&&(Dpb(b,h),g.tv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.sV.prototype.load.call(this);Apb(this,this.player.Rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.tC()&&(a=Epb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Ma.get(d);f&&Fpb(e,f);f=f&&(f.BN||f.WH);if(!c.Qu||f)c.Va?Bpb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.nT(h))&&!b.qa&&Jpb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.ZT(this.player,this.C.element,4);this.qK();(f=g.oT(c))&&Ipb(this,f);(f=g.fWa(c))&&f.featuredChannel&&Mpb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Tg=g.tf("ytp-cards-button",this.player.getRootNode());g.nT(c)&&Jpb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&Bpb(this,b.Va,a)};
g.k.unload=function(){this.player.sf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,G3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.sV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.l_=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Gpb(this):this.load())};
g.k.Hk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.qa};
g.k.fp=function(){return!!this.j&&this.j.C};
g.k.BB=function(a,b,c){b=void 0===b?!1:b;this.Hk();this.j&&(a?c?d4(this.j,c,b):d4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e4(this.j))};
g.k.AB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Ma.unsubscribe("vast_info_card_add",this.l_,this);g.vv(this.player.getRootNode(),g.KY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Zu,c=0,d=a.length;c<d;c++)b.Mj(a[c]);this.ra.length=0;g.sV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.rV("annotations_module",ypb);g.rV("creatorendscreen",tob);})(_yt_player);
